### ISSUE TITLE
Aborted (core dumped)

### ISSUE THREAD

**Issue by xinkwu** [suhrig/pingpongpro#1]
I used pingpongpro to call the pingpong signal in several small RNA-seq libraries.
Some libraries could generate ping-pong_signatures.tsv, but some libraries returned the following error messages:

/fsimb/groups/imb-bioinfocf/projects/cf_internal/imb_cf_2013_06_uhrig_BSc_project_pirna/source/seqan/seqan-trunk/core/include/seqan/stream/stream_bgzf.h:1055 FAILED!  (Error reading block in streamEof().)

stack trace:
  0          [0x42aede]  seqan::ClassTest::fail() + 0xe
  1          [0x443536]  pingpongpro()
  2          [0x42962d]  countReadsInBamFile(seqan::BamStream&, std::map<unsigned int, std::map<unsigned int, TReadStack, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, TReadStack> > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::map<unsigned int, TReadStack, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, TReadStack> > > > > > (&) [2], unsigned int, unsigned int, TCountMultiHits, double&) + 0x14d
  3          [0x41e0c6]  main + 0x336
  4    [0x7f34583d7b35]  __libc_start_main + 0xf5
  5          [0x41f3d1]  pingpongpro()

Aborted (core dumped)

Was this file too big? How can I avoid this problem? Thanks!

**Comment by suhrig** [comment]
Hi Kai,

What makes you think the file was too big? Did the program fail on particularly big files?

Are you using the 32bit or the 64bit executable? The 32bit version is sufficient for most small RNA-Seq samples, because they are typically not bigger than a few 100 MB, but there is an architecture-inherent memory limit (2GB) and you might want to try the 64bit version instead.

If this does not solve the issue, can you provide me with a minimal example dataset so that I can reproduce the issue and track down the cause?

Regards,
Sebastian
