### ISSUE TITLE
Cannot install the pingpongpro

### ISSUE THREAD

**Issue by SofiaZhangtj** [suhrig/pingpongpro#3]
Hi Sabastian,
I really like your algorithm, and I think it must be helpful in my project. But I cannot install it successfully now. The method introduced in the manual cannot be used.  The install command: svn co https://github.com/seqan/seqan/branches/master seqan-trunk doesn't work. Cause seqan/branches/master seems have been removed by seqan. I've tried the new version of seqan but I failed. Could you update a new version of Installation guide if possible? I tried the file from bin on my personal computer. It actually works. But when I don't have root, the "./pingpongpro: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory" was received? Is this because I didn't install some packages? Thank you. 
Best wishes,
Sofia

**Comment by suhrig** [comment]
Hi Sofia,

> error while loading shared libraries: libz.so.1

The problem is that libz is not installed on your system. Compiling from source will not help you with this. You have three options:

1. Install libz on the computer where you want to run pingpongpro (requires root privileges).
2. Copy `libz.so.1` from your personal computer, where the file is apparently available, otherwise pingpongpro wouldn't run there either. To find out where `libz.so.1` is located on your personal computer use the command `ldd pingpongpro`. Copy the file to the target computer, e.g. to `/home/sofia/mylibs`. Then set the following environment variable: `export LD_LIBRARY_PATH=/home/sofia/mylibs:$LD_LIBRARY_PATH`.
3. Compile `libz.so.1` yourself. This option is a bit complicated. Here are the steps, which should be run on the target computer:

```
wget -O - https://zlib.net/zlib-1.2.11.tar.gz | tar -xzf -
cd zlib-1.2.11
./configure
make shared
```

Afterwards, set `LD_LIBRARY_PATH` to `/complete/path/to/zlib-1.2.11` as explained in option 2.

Regards,
Sebastian

**Comment by SofiaZhangtj** [comment]
Hi Sebastian,
I appreciate your answer, and it works on my computer. Thank you.
Best wishes,
Sofia
